# fly.toml app configuration file generated for nextjs-waitlist-page on 2024-04-01T19:06:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextjs-waitlist-page'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
